 @@ hightlight id_;_Browser("Open an account - Franklin").Page("Open an Account").Frame("a7vtcrow36p6").WebElement("Select all images with")_;_script infofile_;_ZIP::ssf21.xml_;_
Browser("Mutual Funds | Investments").Page("Google").WebEdit("Search").Set "franklin templeton" @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Google").WebEdit("Search")_;_script infofile_;_ZIP::ssf22.xml_;_
Browser("Mutual Funds | Investments").Page("Google").WebEdit("Search").Submit @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Google").WebEdit("Search")_;_script infofile_;_ZIP::ssf23.xml_;_
Browser("Mutual Funds | Investments").Page("franklin templeton - Google").Link("- Trustworthy SiteThis").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("franklin templeton - Google").Link("- Trustworthy SiteThis")_;_script infofile_;_ZIP::ssf24.xml_;_
Browser("Mutual Funds | Investments").Page("Mutual Funds | Investments").Link("Learn More_2").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Mutual Funds | Investments").Link("Learn More 2")_;_script infofile_;_ZIP::ssf25.xml_;_
Browser("Mutual Funds | Investments").Page("Open an account - Franklin_3").WebRadioGroup("acctType").Select "rothIRA" @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an account - Franklin 3").WebRadioGroup("acctType")_;_script infofile_;_ZIP::ssf26.xml_;_
Browser("Mutual Funds | Investments").Page("Open an account - Franklin_3").WebButton("Next").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an account - Franklin 3").WebButton("Next")_;_script infofile_;_ZIP::ssf27.xml_;_
Browser("Mutual Funds | Investments").Page("Open an account - Franklin_2").WebButton("Next").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an account - Franklin 2").WebButton("Next")_;_script infofile_;_ZIP::ssf28.xml_;_
Browser("Mutual Funds | Investments").Page("Open an Account").WebRadioGroup("optactiveUser").Select "No" @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an Account").WebRadioGroup("optactiveUser")_;_script infofile_;_ZIP::ssf29.xml_;_
Browser("Mutual Funds | Investments").Page("Open an Account").WebButton("Next").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an Account").WebButton("Next")_;_script infofile_;_ZIP::ssf30.xml_;_
