 @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an Account").Link("Contact Us")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("Mutual Funds | Investments").Page("Mutual Funds | Investments").WebButton("products--planning").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Mutual Funds | Investments").WebButton("products--planning")_;_script infofile_;_ZIP::ssf10.xml_;_
Browser("Mutual Funds | Investments").Page("What is a Mutual Fund?").Link("Learn More").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("What is a Mutual Fund?").Link("Learn More")_;_script infofile_;_ZIP::ssf11.xml_;_
Browser("Mutual Funds | Investments").Page("Fixed Income Funds & Investmen").Link("Open An Account").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Fixed Income Funds & Investmen").Link("Open An Account")_;_script infofile_;_ZIP::ssf12.xml_;_
Browser("Open an account - Franklin").Page("Open an account - Franklin").Link("Open Retirement Account").Click @@ hightlight id_;_Browser("Open an account - Franklin").Page("Open an account - Franklin").Link("Open Retirement Account")_;_script infofile_;_ZIP::ssf13.xml_;_
Browser("Open an account - Franklin").Page("Open an account - Franklin").WebElement("Traditional IRA").Click @@ hightlight id_;_Browser("Open an account - Franklin").Page("Open an account - Franklin").WebElement("Traditional IRA")_;_script infofile_;_ZIP::ssf14.xml_;_
Browser("Open an account - Franklin").Page("Open an account - Franklin").WebRadioGroup("acctType").Select "traditionalIRA" @@ hightlight id_;_Browser("Open an account - Franklin").Page("Open an account - Franklin").WebRadioGroup("acctType")_;_script infofile_;_ZIP::ssf15.xml_;_
Browser("Open an account - Franklin").Page("Open an account - Franklin").WebButton("Next").Click @@ hightlight id_;_Browser("Open an account - Franklin").Page("Open an account - Franklin").WebButton("Next")_;_script infofile_;_ZIP::ssf16.xml_;_
Browser("Open an account - Franklin").Page("Open an account - Franklin_2").WebButton("Next").Click @@ hightlight id_;_Browser("Open an account - Franklin").Page("Open an account - Franklin 2").WebButton("Next")_;_script infofile_;_ZIP::ssf17.xml_;_
Browser("Open an account - Franklin").Page("Open an Account").WebElement("No").Click @@ hightlight id_;_Browser("Open an account - Franklin").Page("Open an Account").WebElement("No")_;_script infofile_;_ZIP::ssf18.xml_;_
Browser("Open an account - Franklin").Page("Open an Account").WebRadioGroup("optactiveUser").Select "No" @@ hightlight id_;_Browser("Open an account - Franklin").Page("Open an Account").WebRadioGroup("optactiveUser")_;_script infofile_;_ZIP::ssf19.xml_;_
Browser("Open an account - Franklin").Page("Open an Account").WebButton("Next").Click @@ hightlight id_;_Browser("Open an account - Franklin").Page("Open an Account").WebButton("Next")_;_script infofile_;_ZIP::ssf20.xml_;_
 @@ hightlight id_;_Browser("Open an account - Franklin").Page("Open an Account").Frame("a7vtcrow36p6").WebElement("Select all images with")_;_script infofile_;_ZIP::ssf21.xml_;_
