 @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an Account").WebButton("Next")_;_script infofile_;_ZIP::ssf30.xml_;_
Browser("Mutual Funds | Investments").Page("Google").WebEdit("Search").Set "franklin templeton" @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Google").WebEdit("Search")_;_script infofile_;_ZIP::ssf31.xml_;_
Browser("Mutual Funds | Investments").Page("Google").WebEdit("Search").Submit @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Google").WebEdit("Search")_;_script infofile_;_ZIP::ssf32.xml_;_
Browser("Mutual Funds | Investments").Page("franklin templeton - Google_2").Link("Franklin Templeton Investments").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("franklin templeton - Google 2").Link("Franklin Templeton Investments")_;_script infofile_;_ZIP::ssf33.xml_;_
Browser("Mutual Funds | Investments").Page("Mutual Funds | Investments").Link("Learn More_2").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Mutual Funds | Investments").Link("Learn More 2")_;_script infofile_;_ZIP::ssf34.xml_;_
Browser("Mutual Funds | Investments").Page("Open an account - Franklin").Link("Open Retirement Account").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an account - Franklin").Link("Open Retirement Account")_;_script infofile_;_ZIP::ssf35.xml_;_
Browser("Mutual Funds | Investments").Page("Open an account - Franklin").WebElement("Roth IRA").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an account - Franklin").WebElement("Roth IRA")_;_script infofile_;_ZIP::ssf36.xml_;_
Browser("Mutual Funds | Investments").Page("Open an account - Franklin").WebRadioGroup("acctType").Select "rothIRA" @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an account - Franklin").WebRadioGroup("acctType")_;_script infofile_;_ZIP::ssf37.xml_;_
Browser("Mutual Funds | Investments").Page("Open an account - Franklin").WebButton("Next").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an account - Franklin").WebButton("Next")_;_script infofile_;_ZIP::ssf38.xml_;_
Browser("Mutual Funds | Investments").Page("Open an account - Franklin_2").WebButton("Next").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an account - Franklin 2").WebButton("Next")_;_script infofile_;_ZIP::ssf39.xml_;_
Browser("Mutual Funds | Investments").Page("Open an Account").WebRadioGroup("optactiveUser").Select "No" @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an Account").WebRadioGroup("optactiveUser")_;_script infofile_;_ZIP::ssf40.xml_;_
Browser("Mutual Funds | Investments").Page("Open an Account").WebButton("Next").Click @@ hightlight id_;_Browser("Mutual Funds | Investments").Page("Open an Account").WebButton("Next")_;_script infofile_;_ZIP::ssf41.xml_;_
